Update item.h
FinneganThompson/CSCI1300Project3 pull request #3
Opened 2023-04-22 20:34 UTC by AugustMill

2023-04-22 20:42 UTC, FinneganThompson requested changes

2023-04-22 20:42 UTC, FinneganThompson commented on item.h
> +        bool useCookware(vector<cookware> cookwares_, int vectPos); // Returns false is cookware breaks and removes from vector
Why does the use cookware take in a vector of cookware? Isn't it a member of each cookware instance? This might be better as a function of inventory.

2023-04-22 20:42 UTC, FinneganThompson commented on item.h
> +        int ingredients;
format should be var_ for private data members

2023-04-22 20:42 UTC, FinneganThompson commented on item.h
> +        int armor;
Yeah that definitely makes more sense for the armor.

2023-04-22 20:42 UTC, FinneganThompson commented on item.h
> +        void ChangeQuantity(int type, int quantChange); // changes the amount of that type of treasure
maybe call it changeTreasureQuantity just for clarity

2023-04-22 21:04 UTC, AugustMill commented on item.h
> +        bool useCookware(vector<cookware> cookwares_, int vectPos); // Returns false is cookware breaks and removes from vector
ah good catch, i'll move it

2023-04-22 21:04 UTC, AugustMill commented on item.h
> +        int ingredients;
sounds good

2023-04-22 21:04 UTC, AugustMill commented on item.h
> +        void ChangeQuantity(int type, int quantChange); // changes the amount of that type of treasure
good catch

2023-04-22 21:06 UTC, FinneganThompson commented on item.h
> -        bool removeCookware(int cookwareToRemove); // Removes cookware. Returns success
I think removeArmor and removeCookware are still needed since they are private data members

2023-04-22 21:46 UTC, AugustMill commented on item.h
> -        bool removeCookware(int cookwareToRemove); // Removes cookware. Returns success
fair, how do you feel about it being a void though, we can always come back to change it if needed, but it seems like we may not need a return type

2023-04-23 17:12 UTC, FinneganThompson commented on item.h
> -        bool removeCookware(int cookwareToRemove); // Removes cookware. Returns success
I've been using the bool as a check to see if it's possible to remove that much of a certain item. I guess it's not necessary but it might be able to save some time. If it would be easier for you to have it be void then go ahead

2023-04-24 17:39 UTC, merged